### ISSUE TITLE
Signature mismatch using swarm-testing

### ISSUE THREAD

**Issue by GiorgioRegni** [scality/Zenko#14] opened 2017-07-18 08:02 UTC
I ran a vanilla swarm-testing environment and going through the frontend ngnix doesn't work, getting a sig mismatch. Going direct through s3server as opposed to ngninx works so I bet that the ngninx config strips some headers/breaks the signature calculation.

> GMBP:swarm-testing giorgio$ aws s3 --endpoint http://localhost:80 mb s3://bucket1 --region=us-east-1
> make_bucket failed: s3://bucket1 An error occurred (SignatureDoesNotMatch) when calling the CreateBucket operation: The request signature we calculated does not match the signature you provided.
> GMBP:swarm-testing giorgio$ vim docker-stack.yml 
> GMBP:swarm-testing giorgio$ less docker-stack.yml 
> GMBP:swarm-testing giorgio$ docker stack deploy -c docker-stack.yml zenko-testing
> Updating service zenko-testing_lb (id: amkd4cnwzlyhgi2jz3yote6lr)
> Updating service zenko-testing_s3 (id: tyalfqm8taia7u3l0zdrsbunc)
> GMBP:swarm-testing giorgio$ aws s3 --endpoint http://localhost:8000 mb s3://bucket1 --region=us-east-1
> make_bucket: bucket1

**Comment by baslking** [comment] 2017-07-25 08:51
This is the same as the other issue (don't use :80 for default port)

**Comment by LaureVergeron** [comment] 2017-07-27 23:42
Closing as duplicate of #10

**Closed by LaureVergeron** 2017-07-27 23:42 UTC
